variables:
- name: BuildParameters.mavenPOMFile
  value: pom.xml
name: $(date:yyyyMMdd)$(rev:.r)

on:
push:
  branches: [ main ]
pull_request:
  branches: [ main ]

jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Default
  steps:
  - name: Azure Pipelines Action
    uses: Azure/pipelines@v1
    with:
      azure-devops-project-url: https://dev.azure.com/slchandima/pipelineTest
      azure-pipeline-name: 'pipelineTest-Maven-CI'
      azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
...